run:
  tests: false
  timeout: 10m
issues:
  exclude: 
    - ST1000 
linter-settings:
  exhaustive:
    default-signifies-exhaustive: true
  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    # Default: 30
    max-func-lines: 10
  revive:
    enable-all-rules: true
    # Disabled rules
    rules:
      - name: blank-imports
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: add-constant
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: bare-return
        disabled: true
      - name: redundant-import-alias
        disabled: true
  gocritic:
    disabled-checks:
      - commentedOutCode
      - docStub
      - hugeParam
      - whyNoLint
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  sloglint:
    no-mixed-args: true
    attr-only: true
    context-only: true
    static-msg: true
    key-naming-case: snake
linters:
  enable:
   - asasalint
   - asciicheck
   - bidichk
   - bodyclose
   - contextcheck
   - dupl
   - durationcheck
   - errcheck
   - errname
   - errorlint
   - execinquery
   - exhaustive
   - exportloopref
   - forcetypeassert
   - gocheckcompilerdirectives
   - gochecknoglobals
   - gochecknoinits
   - goconst
   - gocritic
   - godot
   - goerr113
   - gofumpt
   - gosec
   - gosimple
   - govet
   - grouper
   - importas
   - ineffassign
   - intrange
   - ireturn
   - loggercheck
   - makezero
   - musttag
   - nestif
   - nilerr
   - noctx
   - prealloc
   - predeclared
   - reassign
   - revive
   - rowserrcheck
   - sloglint
   - sqlclosecheck
   - staticcheck
   - stylecheck
   - typecheck
   - unconvert
   - unused
   - unparam
   - usestdlibvars
   - wastedassign
   - whitespace
   - wrapcheck
